# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Interject Documentation Site
email: EugeneL@gointerject.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: / # the subpath of your site, e.g. /blog
# url: https://gointerject.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dukog
github_username:  lyubar

# Build settings
name: Interject Documentation
markdown: kramdown
theme: minima
url: "https://docs.gointerject.com/" # the base hostname & protocol for your site
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - parse_block_html

  # - jekyll-responsive-image

  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jemoji
  # - jekyll-archives

# gem:
#   - jekyll-srcset
google:
  search_engine_id: 005534451279647379552:p216o8yqyva
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: custom
      toc_min: 2
      toc_max: 3
      tree: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

repository:
  GoInterject/gointerject

encoding:
  UTF-8

exclude: [vendor]

